[package]
name = "sisurf-python"
version.workspace = true
edition.workspace = true

[lib]
name = "sisurf"
crate-type = ["cdylib"]

[dependencies]
sisurf-core = { path = "../core" }
pyo3 = { version = "0.28", features = ["extension-module"] }
tokio.workspace = true
futures.workspace = true
serde_json.workspace = true
